### ISSUE TITLE
Cannot use via include_role

### ISSUE THREAD

**Issue by muff1nman** [oVirt/ovirt-ansible-hosted-engine-setup#192] opened 2019-05-16 15:55 UTC
Got an error when using role via include_role:

```
$ ansible-playbook -i inventory/ --limit pointblank playbooks/ovirt-hosted-engine.yml

PLAY [Deploy oVirt hosted engine] *****************************************************************************************************************

TASK [Gathering Facts] ****************************************************************************************************************************
ok: [pointblank]

TASK [include_role : ovirt.hosted-engine-setup] ***************************************************************************************************

TASK [ovirt.hosted-engine-setup : Install oVirt Hosted Engine packages] ***************************************************************************
ok: [pointblank]

TASK [ovirt.hosted-engine-setup : System configuration validations] *******************************************************************************
included: /home/andrew/automate/roles/ovirt.hosted-engine-setup/tasks/pre_checks/001_validate_network_interfaces.yml for pointblank => (item=/home/andrew/automate/roles/ovirt.hosted-engine-setup/tasks/pre_checks/001_validate_network_interfaces.yml)
ERROR! Unexpected Exception, this is probably a bug: 'NoneType' object has no attribute 'rfind'
to see the full traceback, use -vvv

```
Reproduce playbook:

```
---
- name: Deploy oVirt hosted engine
  hosts: all
  tasks:
    - include_role:
        name: ovirt.hosted-engine-setup
```

Ansible version:

```
$ ansible-playbook --version
ansible-playbook 2.7.10
  config file = /home/andrew/automate/ansible.cfg
  configured module search path = [u'/home/andrew/automate/library']
  ansible python module location = /usr/lib/python2.7/site-packages/ansible
  executable location = /usr/bin/ansible-playbook
  python version = 2.7.5 (default, Sep 12 2018, 05:31:16) [GCC 4.8.5 20150623 (Red Hat 4.8.5-36)]
```

**Comment by tiraboschi** [comment] 2019-05-28 14:44
@muff1nman I'm not able to reproduce it; can you please try with -vvv and attach the output?

**Comment by sandrobonazzola** [comment] 2020-06-09 10:17
Closing as we can't reproduce and needed info were not provided. Please reopen if still relevant

**Closed by sandrobonazzola** 2020-06-09 10:17 UTC
